version: '3.4'

services:
  web:
    container_name: web
    build: ./web
    ports:
      - "8000:80"
    depends_on:
      - db-oaipmh
  db-oaipmh:
    container_name: db-oaipmh
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=verhalenbank_omeka
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
  phpmyadmin:
    container_name: phpmyadmin
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - 8080:80
    depends_on:
      - db-oaipmh
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=db-oaipmh
